### ISSUE TITLE
Starting debugging on Neon fails

### ISSUE THREAD

**Issue by jzsig** [gnuarmeclipse/qemu#14]
When I go through the blinky tutorial and try to debug with QEMU, I get the following error:

Could not determine GDB version after sending: arm-none-eabi-gdb --version, response: 

I made sure that the toolchain was pointed to the correct location, and it is, so I'm not sure what the problem is.

**Comment by jzsig** [comment]
I fixed the above problem by installing the correct 32 bit drives for gdb, but now I'm getting an error:

An internal error occured during: "Launching blinky".
org.eclipse.cdt.dsf.gdb.service.GdbDebugServicesFactory.<init>(Ljava/lang/String;)V

**Comment by ilg-ul** [comment]
In the README FIRST issue #1 are listed some details regarding your configuration.

I do not know what '32-bit drives for gdb' you are talking about.

**Comment by jzsig** [comment]
Sorry about that, here is the requested info:

QEMU Version: 2.4.50
System Version: Centos 2.10 64-bit
Command Line: Sent from eclipse, not sure how to find exact command. 

Here is screenshot:
[http://imgur.com/y6nvyr1](url)

I have actually determined that it is not QEMU its self since I can use the command line interface and it works i.e. using 

./qemu-system-gnuarmeclipse -board STM32F4-Discovery -mcu STM32F407VG --image /home/jzsig/workspace/blinky/Debug/blinky.elf 

However, when I try and debug from eclipse, it does nothing and gives the GDB error above. The 32-bit drivers I was referring to 32 bit libraries that were needed to run GDB.

**Comment by ilg-ul** [comment]
> Command Line: Sent from eclipse, not sure how to find exact command.

right click on the qemu process in the Debug tab, the Debug perspective

> Here is screenshot:

this looks like an Eclipse problem.

check the Eclipse log (workspace/.metadata/.log) for more info; check the definitions of the qemu path and executable macros, maybe you have a wrong character there.

**Comment by jzsig** [comment]
Yeah it was a problem with eclipse. I resolved the problem by switching to Mars instead of Neon.

**Comment by ilg-ul** [comment]
so the conclusion is that the qemu plug-in does not run on Neon? can you try again with a fresh Neon, without any other plug-ins or custom settings?

**Comment by jzsig** [comment]
Correct, thats what it seems like. I did a freash install received the same problem. It was giving the same error above for the qemu plugin as well as the j-link plugin.

**Comment by ilg-ul** [comment]
thank you, in this case I have to investigate the plug-ins behaviour on Neon.

**Comment by ilg-ul** [comment]
The Neon debugging issues were fixed in the previous release (https://github.com/gnuarmeclipse/plug-ins/pull/120), can you confirm everything is ok now?
