### ISSUE TITLE
Compilation fails with SDL disable

### ISSUE THREAD

**Issue by npereiras** [gnuarmeclipse/qemu#18]
Compiling for platforms without SDL available fails. 
`configure --target-list=gnuarmeclipse-softmmu --static --disable-sdl`

This is due to SDL code not correctly protected.

Here is a fast patch based on gnuarmeclipse-dev. [sdl.txt](https://github.com/gnuarmeclipse/qemu/files/343234/sdl.txt)

**Comment by ilg-ul** [comment]
thank you for the patch.

why do you need the `GPIO_LED_STATE(dev);` in `gpio_led_realize_callback()`?

**Comment by npereiras** [comment]
You can remove it. It’s not needed.

Thank you

**Comment by ilg-ul** [comment]
ok, applied.
