### ISSUE TITLE
GNU ARM Eclipse QEMU v2.6.0-20160728 on Ubuntu 14.04LTS

### ISSUE THREAD

**Issue by ivlz** [gnuarmeclipse/qemu#25]
I followed the instructions at http://gnuarmeclipse.github.io/qemu/install/ and installed v2.6.0-20160728. However it fails to launch in Eclipse and on the command line. 

Eclipse GUI reports:
"QEMU failed with code (-1).
For more details, see the qemu-system-gnuarmeclipse console."

Eclipse QEMU console reports:
GNU ARM Eclipse 64-bits QEMU v2.6.0 (qemu-system-gnuarmeclipse).
Board: 'generic' (Generic Cortex-M board; use -mcu to define the device).
Device: 'STM32F103RB' (Cortex-M3 r0p1, MPU), Flash: 128 kB, RAM: 20 kB.
Command line: 'testqemu' (8 bytes).
Cortex-M3 r0p1 core initialised.

Commandline reports:

> /opt/gnuarmeclipse/qemu/2.6.0-201607280535/bin/qemu-system-gnuarmeclipse -board generic -mcu STM32F103RB --image testqemu.elf
> qemu-system-gnuarmeclipse: /Host/Work/qemu/gnuarmeclipse-qemu.git/hw/cortexm/peripheral.c:281: peripheral_realize_callback: Assertion `state->max_offset_bytes < state->mmio_size_bytes' failed.
> Aborted (core dumped)

I then followed the same instructions to install v2.4.50-201510290935-dev. This works perfectly in both Eclipse and the command line.

Is it possible there is a bug in the latest release or have I misstepped somewhere?

Thanks.

MACHINE SETUP:

> uname -a
> Linux workstation0 4.4.0-36-generic #55~14.04.1-Ubuntu SMP Fri Aug 12 11:49:30 UTC 2016 x86_64 x86_64 x86_64 GNU/Linux
> 
> ls /opt/gnuarmeclipse/qemu
> 2.4.50-201510290935-dev  2.6.0-201607280535

**Comment by ilg-ul** [comment]
I confirm the issue, it is a bug.

in the latest release I applied a patch to initialise all available USARTs in the device, and this worked properly for F4, but for F1 the USARTs are not yet implemented, and the assert triggered.

the workaround was to temporarily remove the capabilities related to USARTs in all other devices than F4.

the repository is up-to-date now, it you want you can build the Linux version.

otherwise I plan to update QEMU to 2.7 in a few weeks time and make a new release, which will include this patch too.

**Comment by ivlz** [comment]
Thank you for the prompt and helpful response.

**Comment by ilg-ul** [comment]
fixed in v2.7.0-20161029

**Comment by ivlz** [comment]
Hi Liviu
    Thanks for hthe fix. It works.
    
    Regards
    Inno.
    
    On 28/11/16 21:27, Liviu Ionescu wrote:
    
    
      Closed #25.
      —
        You are receiving this because you authored the thread.
        Reply to this email directly, view
          it on GitHub, or mute
          the thread.
      
        
          
          
        
        
      
      {"api_version":"1.0","publisher":{"api_key":"05dde50f1d1a384dd78767c55493e4bb","name":"GitHub"},"entity":{"external_key":"github/gnuarmeclipse/qemu","title":"gnuarmeclipse/qemu","subtitle":"GitHub repository","main_image_url":"https://cloud.githubusercontent.com/assets/143418/17495839/a5054eac-5d88-11e6-95fc-7290892c7bb5.png","avatar_image_url":"https://cloud.githubusercontent.com/assets/143418/15842166/7c72db34-2c0b-11e6-9aed-b52498112777.png","action":{"name":"Open in GitHub","url":"https://github.com/gnuarmeclipse/qemu"}},"updates":{"snippets":[{"icon":"DESCRIPTION","message":"Closed #25."}],"action":{"name":"View Issue","url":"https://github.com/gnuarmeclipse/qemu/issues/25#event-874315055"}}}

**Comment by ivlz** [comment]
Thanks for the fix. I can confirm that it works.

**Comment by ilg-ul** [comment]
FYI, some major internal changes are under way, so I would appreciate if you could also test the future releases.

**Comment by ilg-ul** [comment]
could you check the latest release (2.8) and confirm if it is ok?
