### ISSUE TITLE
If my code can't fit in my emulated MCU's flash, can I increase somehow?

### ISSUE THREAD

**Issue by vjpr** [gnuarmeclipse/qemu#45]
Just a quick question...

When I compile for code coverage or when I wrap function calls (i.e. things that I wouldn't do when running on real hardware), my code is too big for the flash.

Seeing as QEMU is emulating the MCU, is there a way I can get my code to fit without making changes to my code (or only making some simple changes)?

**Comment by ilg-ul** [comment]
as far as I rememeber, there were some command line options to specify the memory size, but I don't remember them, and I don't know if they apply to flash.

generally the recomended use case for qemu is to emulate images that were already functional on physical hardware.

for general support and further questions, please use the project forum.
