### ISSUE TITLE
Perhaps influence on the periphery from the outside?

### ISSUE THREAD

**Issue by ghost** [gnuarmeclipse/qemu#54]
MCU QEMU emulates GPIO operation, for example, can the status of these pins be influenced from another program? For example, running emulation in QEMU, and passing it to that, for example on a certain pin, this state.

**Comment by ilg-ul** [comment]
yes, the status of GPIO pins can be influenced from outside events.

right now it is possible to push buttons on the graphical image of the board and change the status of GPIO pins, or even trigger interrupts.

as with any software, there are many possibilities. but it is a matter of resources which of these possibilities ever get implemented.
