### ISSUE TITLE
STM32F303 board

### ISSUE THREAD

**Issue by patrickelectric** [gnuarmeclipse/qemu#55]
Hi, it appears that [boards-discovery](https://github.com/gnu-mcu-eclipse/qemu/blob/10186b90af2054f41cd637048e4609e21775d938/hw/cortexm/stm32/boards-discovery.c) don't ahave any update with stm32f303. This implementation is working ? Is it possible to test it or improve ?

**Comment by ilg-ul** [comment]
there are some updates planned for qemu, and after this it might be possible to also update the discovery boards, but I cannot commit on any date.

**Comment by ilg-ul** [comment]
for other questions and support, please use the project forum.
