### ISSUE TITLE
QEMU failed with code (1)

### ISSUE THREAD

**Issue by jiapei100** [gnuarmeclipse/qemu#59]
Failed to emulate STM32F429ZI... Please refer to the following image:

[http://longervision.com/questions/qemu.jpg](http://longervision.com/questions/qemu.jpg)

Please help ...

**Comment by jiapei100** [comment]
`~/opt/xPacks/@gnu-mcu-eclipse/qemu/2.8.0-3.1/.content/bin/qemu-system-gnuarmeclipse -board STM32F429I-Discovery --image F429ZI_OV5640.elf`

The above command line is working ...
It may have something to do with the board name **STM32F429I-Discovery** ?

Cheers
Pei

**Comment by ilg-ul** [comment]
> It may have something to do with the board name...?

I don't know what you mean, as long as you enter it correctly it should work.
