### ISSUE TITLE
qemu-system-gnuarmeclipse: cortex-m4 stm32 - how can I communicate between peripheral?

### ISSUE THREAD

**Issue by MarkOstis** [gnuarmeclipse/qemu#67]
Hi Guys,

I am trying to add the SPI and DMA peripherals to qemu-system-gnuarmeclipse stm32. I have already added initialization of the SPI and DMA. Now I am thinking, how two different peripherals can communicate between them-self.

From the STM32F4 datasheet the SPI should notify the DMA that the data has been sent. So, does QEMU is able to raise event via SPI which will be handled by DMA?

Thanks!

**Comment by ilg-ul** [comment]
I have no experience with DMA on QEMU, I suggest you take a look at the more complicated devices, the existing Cortex-M devices do not support DMA.

But even if you manage to enable DMA for SPI, to what device will it communicate?

---

For other questions and support, please use the project forum.
