### ISSUE TITLE
Blinky on QEMU with STM32F1 fails

### ISSUE THREAD

**Issue by cooked** [gnuarmeclipse/qemu#69]
### Description

The default blinky project used to [test the correct functioning of QEMU](https://gnu-mcu-eclipse.github.io/tutorials/blinky-arm/) does not work for the STM32F1 targets. 

### Steps to Reproduce
1. create new project from File>New>Others
2. selected C++ Project and the STM32F10x Executable template with the ARM Cross GCC toolchain
3. select default target options as below
![image](https://user-images.githubusercontent.com/1381353/58584089-c591ab80-8255-11e9-8667-058961fc8157.png)
4. select folders settings default,
5. create Debug/Release configurations default GNU MCU Eclipse ARM Embedded GCC (arm-none-eabi-gcc) toolchain and complete
6. built the project, Debug configuration
7. assigned the NUCLEO STM32F103RB device (or equivalent NUCLEO board) to the project
![image](https://user-images.githubusercontent.com/1381353/58584315-4c468880-8256-11e9-869d-c2b3de2ba87d.png)
8. create and launch debug config
![image](https://user-images.githubusercontent.com/1381353/58584340-5ff1ef00-8256-11e9-8cfd-939268fe644d.png)

**Expected behaviour:** 
QEMU to run the blinky project succesfully

**Actual behaviour:**
QEMU throws the following error

![image](https://user-images.githubusercontent.com/1381353/58584435-90d22400-8256-11e9-8b81-394512913d7b.png)

### Versions

* QEMU package version :  2.8.0-6
* QEMU plug-in version:  3.3.3.201901011632
* Eclipse version: 4.11.0
* Java version: OpenJDK 1.8.0_212 64 bit
* operating system: Linux Debian 64bit
* toolchain version: 8.2.1-1.7-20190524-0606

**Comment by cooked** [comment]
Also the STM32F0x seems to fail in a similar way.

**Comment by ilg-ul** [comment]
thank you, I'll investigate.

**Comment by randre70** [comment]
Also applies to Windows version. Tried several configuration options of cpu and qemu to no avail.
![image](https://user-images.githubusercontent.com/6505918/63001726-89dda980-be74-11e9-9536-a77a61198540.png)
![image](https://user-images.githubusercontent.com/6505918/63001758-9bbf4c80-be74-11e9-953a-4e3bb53ffadd.png)

**Comment by ilg-ul** [comment]
could you try the latest version? it is available from 

https://github.com/xpack-dev-tools/qemu-arm-xpack/releases

**Comment by randre70** [comment]
Same error
![image](https://user-images.githubusercontent.com/6505918/63006748-83a0fa80-be7f-11e9-9f93-35d444b3b7a8.png)
![image](https://user-images.githubusercontent.com/6505918/63006821-b814b680-be7f-11e9-8455-a6c5f2bcea75.png)

**Comment by ilg-ul** [comment]
thank you, I entered a new ticket, I'll investigate and try to fix it in the next release.

**Comment by ilg-ul** [comment]
Please check 2.8.0-8 and confirm if the bug was fixed.
