### ISSUE TITLE
LEDs on OLIMEX STM32-P107 board are switched

### ISSUE THREAD

**Issue by T-o-b-i** [gnuarmeclipse/qemu#9]
i already created a branch with a fix but since im not allowed to push i added the patch here:

I also fixed an issue with malloc tracepoints and new glib versions:
(see https://lists.gnu.org/archive/html/qemu-devel/2015-09/msg01262.html)

[OLIMEX_STM32-P103_LED_fix.txt](https://github.com/gnuarmeclipse/qemu/files/148080/OLIMEX_STM32-P103_LED_fix.txt)
[glib_malloc_tracepoint_fix.txt](https://github.com/gnuarmeclipse/qemu/files/148081/glib_malloc_tracepoint_fix.txt)

**Comment by ilg-ul** [comment]
I added you as a contributor, please push the changes on a separate branch, each issue as a separate push.

**Comment by ilg-ul** [comment]
btw, it seems you did not fork the project before trying to generate pull requests.

**Comment by T-o-b-i** [comment]
thx for the hint. never used github before...

**Comment by ilg-ul** [comment]
the pull request should be integrated for now, please confirm it is ok.

**Comment by ilg-ul** [comment]
fixed in 2.6.0-20160728
